# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
#disqus: dbyll
#google_analytics: dbyll
title: Hồng Hà Tech Blog
web: www.hongha.asia
repo: samdx.github.io
defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: Hồng Hà Tech Blog

description: Today-I-Learned
author:
  name: samdx
  email: samdx@hongha.asia
  github: samdx
#  twitter:
#  pinterest:
#  linkedin:
  bio: Power is gained by share knowledge, not hoarding it. - Unknown
#  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

gems:
  - jekyll-paginate
